#!/bin/bash

echo "Fixing all upload and data directory permissions for Mastodon..."
echo ""
echo "Please run these commands with sudo in a separate terminal:"
echo ""
echo "# Fix ownership for all upload directories"
echo "sudo chown -R kanaba:kanaba /home/kanaba/troupex4/mastodon/public/system/"
echo ""
echo "# Set proper permissions"
echo "sudo chmod -R 755 /home/kanaba/troupex4/mastodon/public/system/"
echo ""
echo "# Ensure Rails can write to temp directories"
echo "sudo chown -R kanaba:kanaba /home/kanaba/troupex4/mastodon/tmp/"
echo "sudo chmod -R 755 /home/kanaba/troupex4/mastodon/tmp/"
echo ""
echo "# Fix storage directory if it exists"
echo "if [ -d '/home/kanaba/troupex4/mastodon/storage' ]; then"
echo "  sudo chown -R kanaba:kanaba /home/kanaba/troupex4/mastodon/storage/"
echo "  sudo chmod -R 755 /home/kanaba/troupex4/mastodon/storage/"
echo "fi"
echo ""
echo "This will fix permissions for:"
echo "- Profile picture uploads"
echo "- Header image uploads"
echo "- Media attachments"
echo "- Temporary file storage"