#!/bin/bash

echo "=== Restarting Mastodon Services ==="
echo ""
echo "Please run these commands with sudo in another terminal:"
echo ""
echo "# Restart web server (Puma)"
echo "sudo kill -HUP $(pgrep -f 'puma.*mastodon' | head -1)"
echo ""
echo "# Restart streaming service" 
echo "sudo kill -TERM $(pgrep -f 'node.*streaming' | head -1)"
echo ""
echo "# Restart background workers"
echo "sudo kill -TERM $(pgrep -f 'sidekiq.*mastodon' | head -1)"
echo ""
echo "The services will restart automatically after being killed."
echo ""
echo "After restarting, clear your browser cache and try accessing:"
echo "https://troupex-dev.materiallab.io/"