#!/bin/bash

echo "Starting Mastodon development environment..."
echo "==========================================="
echo ""
echo "This script will help you test the new Showcase feature."
echo ""

# Check if docker-compose is available
if ! command -v docker-compose &> /dev/null; then
    echo "docker-compose not found. Trying with docker compose..."
    COMPOSE_CMD="docker compose"
else
    COMPOSE_CMD="docker-compose"
fi

echo "Step 1: Build custom Docker images with your changes"
echo "-----------------------------------------------------"
echo "Since you want to use custom images with the showcase feature,"
echo "we need to modify docker-compose.yml to build from local code."
echo ""
echo "Run these commands:"
echo ""
echo "1. Edit docker-compose.yml and uncomment the 'build: .' lines for:"
echo "   - web service (line ~61)"
echo "   - streaming service (lines ~83-85)"
echo "   - sidekiq service (line ~104)"
echo ""
echo "2. Build the images:"
echo "   $COMPOSE_CMD build"
echo ""
echo "3. Set up the database (first time only):"
echo "   $COMPOSE_CMD run --rm web rails db:setup"
echo ""
echo "4. Start the services:"
echo "   $COMPOSE_CMD up"
echo ""
echo "5. Access Mastodon at http://localhost:3000"
echo ""
echo "6. Create an account or login"
echo ""
echo "7. Visit any user profile and look for the new 'Showcase' tab!"
echo ""
echo "The tab order will be: Featured | Showcase | Posts | Posts and replies | Media"
echo ""
echo "Note: You'll need to create a .env.production file with basic config:"
echo "  REDIS_HOST=redis"
echo "  DB_HOST=db"
echo "  DB_USER=postgres"
echo "  DB_NAME=postgres"
echo "  LOCAL_DOMAIN=localhost:3000"
echo "  SECRET_KEY_BASE=$(openssl rand -hex 64)"
echo "  OTP_SECRET=$(openssl rand -hex 64)"