name: Deploy TroupeX (Parallel Build)

on:
  push:
    branches: [ main ]
    paths:
      - 'mastodon/**'
      - '.github/workflows/deploy-image-only.yml'
      - 'Dockerfile'
      - 'docker-compose*.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

concurrency:
  group: deploy-${{ github.event.inputs.environment || 'production' }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      web-image: ${{ steps.image.outputs.web-image }}
      streaming-image: ${{ steps.image.outputs.streaming-image }}
      tag: ${{ steps.image.outputs.tag }}
      build-streaming: ${{ steps.changes.outputs.streaming }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check for streaming changes
      id: changes
      run: |
        # Check if streaming files have changed
        # For push events, compare with the before SHA
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..HEAD || echo "")
        else
          # For manual dispatch or first commit, check against previous commit
          CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null || git ls-tree -r --name-only HEAD)
        fi
        
        if echo "$CHANGED_FILES" | grep -q "^mastodon/streaming/"; then
          echo "streaming=true" >> $GITHUB_OUTPUT
          echo "Streaming files changed - will build new image"
        else
          echo "streaming=false" >> $GITHUB_OUTPUT
          echo "No streaming changes - will use existing image"
        fi
    
    - name: Generate image tags
      id: image
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHA_SHORT=${GITHUB_SHA::7}
        TAG="${TIMESTAMP}-${SHA_SHORT}"
        
        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "web-image=${{ env.REGISTRY }}/${OWNER}/troupex-web:${TAG}" >> $GITHUB_OUTPUT
        
        # For streaming, use new tag if changed, otherwise use latest
        if [ "${{ steps.changes.outputs.streaming }}" = "true" ]; then
          echo "streaming-image=${{ env.REGISTRY }}/${OWNER}/troupex-streaming:${TAG}" >> $GITHUB_OUTPUT
        else
          echo "streaming-image=${{ env.REGISTRY }}/${OWNER}/troupex-streaming:latest" >> $GITHUB_OUTPUT
        fi
        
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

  build-web:
    needs: prepare
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push web image
      uses: docker/build-push-action@v5
      with:
        context: ./mastodon
        file: ./mastodon/Dockerfile
        push: true
        tags: |
          ${{ needs.prepare.outputs.web-image }}
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/troupex-web:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          RAILS_ENV=production
          NODE_ENV=production

  build-streaming:
    needs: prepare
    if: needs.prepare.outputs.build-streaming == 'true'
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push streaming image
      uses: docker/build-push-action@v5
      with:
        context: ./mastodon
        file: ./mastodon/streaming/Dockerfile
        push: true
        tags: |
          ${{ needs.prepare.outputs.streaming-image }}
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/troupex-streaming:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

  deploy:
    needs: [prepare, build-web, build-streaming]
    if: always() && needs.prepare.result == 'success' && needs.build-web.result == 'success' && (needs.build-streaming.result == 'success' || needs.build-streaming.result == 'skipped')
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Create deployment files
      run: |
        mkdir -p deployment
        
        # Create volume setup script
        cat > deployment/setup-volumes.sh << 'EOF'
        #!/bin/bash
        set -euo pipefail
        
        echo "=== Setting up TroupeX volumes ==="
        
        # Function to create volume if it doesn't exist
        create_volume_if_not_exists() {
            local volume_name=$1
            if docker volume inspect "$volume_name" >/dev/null 2>&1; then
                echo "Volume '$volume_name' already exists"
            else
                echo "Creating volume '$volume_name'"
                docker volume create "$volume_name"
            fi
        }
        
        # Function to create network if it doesn't exist
        create_network_if_not_exists() {
            local network_name=$1
            local network_type=$2
            if docker network inspect "$network_name" >/dev/null 2>&1; then
                echo "Network '$network_name' already exists"
            else
                echo "Creating network '$network_name'"
                if [ "$network_type" = "internal" ]; then
                    docker network create --internal "$network_name"
                else
                    docker network create "$network_name"
                fi
            fi
        }
        
        # Create all required volumes
        create_volume_if_not_exists "troupex_postgres_data"
        create_volume_if_not_exists "troupex_redis_data"
        create_volume_if_not_exists "troupex_public_system"
        create_volume_if_not_exists "troupex_public_assets"
        create_volume_if_not_exists "troupex_public_packs"
        
        # Create networks
        create_network_if_not_exists "troupex_external" "external"
        create_network_if_not_exists "troupex_internal" "internal"
        
        echo "Volume setup completed!"
        EOF
        
        # Create docker-compose with EXTERNAL volumes
        cat > deployment/docker-compose.yml << 'EOF'
        services:
          db:
            restart: always
            image: postgres:14-alpine
            shm_size: 512mb
            networks:
              - internal_network
            healthcheck:
              test: ['CMD', 'pg_isready', '-U', 'postgres']
            volumes:
              - postgres_data:/var/lib/postgresql/data
            environment:
              - 'POSTGRES_HOST_AUTH_METHOD=trust'

          redis:
            restart: always
            image: redis:7-alpine
            networks:
              - internal_network
            healthcheck:
              test: ['CMD', 'redis-cli', 'ping']
            volumes:
              - redis_data:/data

          web:
            image: ${{ needs.prepare.outputs.web-image }}
            restart: always
            env_file: .env.production
            command: bash -c "rm -f /mastodon/tmp/pids/server.pid && rails db:migrate && rails s -p 3000"
            networks:
              - external_network
              - internal_network
            ports:
              - '3000:3000'
            depends_on:
              - db
              - redis
            volumes:
              - public_system:/mastodon/public/system
              - public_assets:/mastodon/public/assets
              - public_packs:/mastodon/public/packs

          streaming:
            image: ${{ needs.prepare.outputs.streaming-image }}
            restart: always
            env_file: .env.production
            command: node ./streaming
            networks:
              - external_network
              - internal_network
            ports:
              - '4000:4000'
            depends_on:
              - db
              - redis

          sidekiq:
            image: ${{ needs.prepare.outputs.web-image }}
            restart: always
            env_file: .env.production
            command: bundle exec sidekiq
            depends_on:
              - db
              - redis
            networks:
              - external_network
              - internal_network
            volumes:
              - public-system:/mastodon/public/system
              - public-packs:/mastodon/public/packs

        networks:
          external_network:
            name: troupex_external
            external: true
          internal_network:
            name: troupex_internal
            external: true

        volumes:
          postgres_data:
            name: troupex_postgres_data
            external: true
          redis_data:
            name: troupex_redis_data
            external: true
          public_system:
            name: troupex_public_system
            external: true
          public_assets:
            name: troupex_public_assets
            external: true
          public_packs:
            name: troupex_public_packs
            external: true
        EOF
        
        # Create deployment script
        cat > deployment/deploy.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "=== TroupeX Image-Only Deployment ===="
        echo "Web Image: ${{ needs.prepare.outputs.web-image }}"
        echo "Streaming Image: ${{ needs.prepare.outputs.streaming-image }}"
        
        # Ensure we're in the right directory
        cd /home/${USER}/troupex
        
        # IMPORTANT: Set up volumes first (idempotent operation)
        echo "Ensuring volumes exist..."
        chmod +x setup-volumes.sh
        ./setup-volumes.sh
        
        # Pull latest images
        echo "Pulling latest images..."
        docker pull ${{ needs.prepare.outputs.web-image }}
        
        # Only pull streaming if it's a new build
        if [[ "${{ needs.prepare.outputs.streaming-image }}" != *":latest" ]]; then
          echo "Pulling new streaming image..."
          docker pull ${{ needs.prepare.outputs.streaming-image }}
        else
          echo "Using existing streaming:latest image"
        fi
        
        # Stop services before migration to avoid port conflicts
        echo "Stopping services for migration..."
        docker compose stop web streaming sidekiq
        
        # Run database migrations
        echo "Running database migrations..."
        docker compose run --rm --no-deps web rails db:migrate
        
        # Update services
        echo "Starting updated services..."
        docker compose up -d --no-deps web streaming sidekiq
        
        # The zero-downtime scaling doesn't work with port mapping
        # Just do a quick restart which takes < 10 seconds
        
        # Clean up old containers
        echo "Cleaning up..."
        docker container prune -f
        
        # Health check
        echo "Checking health..."
        sleep 10
        docker compose ps
        
        echo "Deployment complete!"
        EOF
        
        chmod +x deployment/deploy.sh

    - name: Pre-deployment backup
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_USER: ${{ secrets.DROPLET_USER }}
      run: |
        echo "Creating pre-deployment backup..."
        ssh -o StrictHostKeyChecking=no ${DROPLET_USER}@${DROPLET_IP} << 'ENDSSH'
          # Check if backup script exists
          if [ -f ~/bin/backup-postgres.sh ]; then
            echo "Running pre-deployment backup..."
            ~/bin/backup-postgres.sh pre-deploy || {
              echo "Warning: Pre-deployment backup failed, but continuing with deployment"
              # Don't fail the deployment if backup fails
            }
          else
            echo "Backup script not found, skipping pre-deployment backup"
          fi
        ENDSSH

    - name: Deploy to server
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_USER: ${{ secrets.DROPLET_USER }}
      run: |
        # Ensure deployment directory exists
        ssh -o StrictHostKeyChecking=no ${DROPLET_USER}@${DROPLET_IP} "mkdir -p /home/${DROPLET_USER}/troupex"
        
        # Upload deployment files
        scp -o StrictHostKeyChecking=no deployment/docker-compose.yml ${DROPLET_USER}@${DROPLET_IP}:/home/${DROPLET_USER}/troupex/
        scp deployment/setup-volumes.sh ${DROPLET_USER}@${DROPLET_IP}:/home/${DROPLET_USER}/troupex/
        scp deployment/deploy.sh ${DROPLET_USER}@${DROPLET_IP}:/home/${DROPLET_USER}/troupex/
        
        # Upload env file
        echo "${{ secrets.PRODUCTION_ENV }}" | base64 -d | ssh ${DROPLET_USER}@${DROPLET_IP} "cat > /home/${DROPLET_USER}/troupex/.env.production"
        
        # Setup Cloudflare tunnel
        ssh ${DROPLET_USER}@${DROPLET_IP} << ENDSSH
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_TUNNEL_CONFIG }}" | base64 -d > ~/.cloudflared/config.yml
          echo "${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}" | base64 -d > ~/.cloudflared/tunnel-creds.json
          chmod 600 ~/.cloudflared/*
          
          # Ensure tunnel is running
          if ! systemctl is-active --quiet cloudflared; then
            sudo cloudflared service install || true
            sudo systemctl start cloudflared
            sudo systemctl enable cloudflared
          fi
        ENDSSH
        
        # Login to GitHub Container Registry on the server
        ssh ${DROPLET_USER}@${DROPLET_IP} << 'ENDSSH'
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        ENDSSH
        
        # Execute deployment
        ssh ${DROPLET_USER}@${DROPLET_IP} "cd /home/${DROPLET_USER}/troupex && bash deploy.sh"

    - name: Verify deployment
      env:
        SITE_URL: ${{ secrets.SITE_URL }}
      run: |
        echo "Waiting for services to stabilize..."
        sleep 30
        
        # Health check
        response=$(curl -s -o /dev/null -w "%{http_code}" ${SITE_URL}/health || echo "000")
        if [ "$response" = "200" ]; then
          echo "✅ Deployment successful! Site is healthy."
        else
          echo "❌ Health check failed (HTTP $response)"
          exit 1
        fi

    - name: Deployment summary
      if: always()
      run: |
        echo "## Deployment Summary"
        echo "- **Environment**: ${{ github.event.inputs.environment || 'production' }}"
        echo "- **Web Image**: ${{ needs.prepare.outputs.web-image }}"
        echo "- **Streaming Image**: ${{ needs.prepare.outputs.streaming-image }}"
        echo "- **Deployed by**: ${{ github.actor }}"
        echo "- **Status**: ${{ job.status }}"